import Link from "next/link";
import { createClassAction, deleteClassAction } from "@/features/workspace/actions";
import { ConfirmDeleteForm } from "@/features/workspace/confirm-delete-form";
import { workspaceData } from "@/features/workspace/data";

export default async function ClassesPage() {
  const { supabase, organizationId } = await workspaceData();
  const { data: classes } = await supabase.from("classes").select("id,name,grade,school_year,shift,subject").eq("organization_id", organizationId).eq("status", "active").order("created_at", { ascending: false });
  return <main className="mx-auto max-w-5xl p-6 sm:p-10"><Link href="/dashboard" className="text-sm font-semibold text-primary">← Painel</Link><h1 className="mt-4 text-3xl font-bold">Turmas</h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_20rem]"><section className="divide-y rounded-xl border bg-background">{classes?.length ? classes.map((item) => <div key={item.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><Link href={`/dashboard/alunos?turma=${item.id}`} className="min-w-0 flex-1 hover:text-primary"><strong>{item.name}</strong><p className="text-sm text-muted-foreground">{item.grade} · {item.subject || "Disciplina não informada"} · {item.school_year}</p></Link><ConfirmDeleteForm action={deleteClassAction} fieldName="classId" value={item.id} message={`Arquivar a turma “${item.name}”? Alunos e avaliações relacionados deixarão de aparecer nas listas, mas os registros serão preservados.`} /></div>) : <p className="p-5 text-muted-foreground">Nenhuma turma cadastrada.</p>}</section><form action={createClassAction} className="space-y-3 rounded-xl border bg-background p-5"><h2 className="font-bold">Nova turma</h2><input required name="name" placeholder="Ex.: 2º ano A" className="h-11 w-full rounded border p-3"/><input required name="grade" placeholder="Série/ano" className="h-11 w-full rounded border p-3"/><input required name="subject" placeholder="Disciplina" className="h-11 w-full rounded border p-3"/><input required name="schoolYear" type="number" defaultValue="2026" className="h-11 w-full rounded border p-3"/><select name="shift" className="h-11 w-full rounded border p-3"><option value="morning">Manhã</option><option value="afternoon">Tarde</option><option value="evening">Noite</option><option value="full_time">Integral</option></select><button className="h-11 w-full rounded bg-primary font-semibold text-white">Salvar turma</button></form></div></main>;
}
